name: Train and Deploy Gujarati QA

on:
  workflow_dispatch:   # Allows you to trigger this manually from GitHub

jobs:

  JOB-1:
    runs-on: ubuntu-latest
    timeout-minutes: 5   # 5 min max

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

  JOB-2:
    needs: JOB-1          # only runs after JOB-1 job finishes
    runs-on: ubuntu-latest
    environment: production   # THIS LINE triggers the approval email to you

    steps:
      - name: Step 1
        run: |
          echo "---- Step 1 ----"

      - name: Step 2
        run: |
          echo "---- Step 2 ----"
      
      - name: Step 3
        run: |
          echo "---- Step 3 ----"